language: python
python: 3.5
sudo: false
cache: pip

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=pypy
  - TOXENV=pyparsing1
  - TOXENV=flask08
  - TOXENV=flask09
  - TOXENV=no-flask-cache
  - TOXENV=coverage
  - TOXENV=lint
  - TOXENV=docs

addons:
  apt:
    packages:
      - libcairo2-dev

install:
  - pip install tox

script: "./.travis.sh"

matrix:
  allow_failures:
    - env: TOXENV=py26
    - env: TOXENV=coverage
    - env: TOXENV=docs
